spring:
   application:
          name: movie-ticket-booking-system-api
    #data resource config file
   datasource:
          url: "${URL:jdbc:mysql://localhost:3306/movie_ticket_booking_system_api?createDatabaseIfNotExist=true}"
          username: "${MYSQL_USERNAME:root}"
          password: "${MYSQL_PASSWORD:root}"
   jpa:
     open-in-view: false
     show-sql: true
     hibernate:
       ddl-auto: update
     properties:
       hibernate:
         format_sql: true
app:
   token:
      secret: "${TOKEN_SECRET:p7ctKoWhIiGRHpyZ+t/YQsb0fXdczx6K49QqClbb0yk=}"
       #only for testing anf development mode